### ISSUE TITLE
Movimentação realizada no mês filtrado mas após fechamento do cartão não é retornada

### ISSUE THREAD

**Issue by gabrielhof** [organizze/api-doc#25]
Tenho uma movimentação realizada no meu cartão de crédito no dia 31/05.
O fatura é fechada no dia 30 de cada mês, então esse lançamento aparecerá somente na fatura paga em julho.

Ao requisitar o endereço `https://api.organizze.com.br/rest/v2/transactions?start_date=2019-05-01&end_date=2019-05-31` a movimentação não é retornada.
Ao tentar requisitar as movimentações do mês seguinte essa movimentação também não aparece.

Estou fazendo algo errado ou é algum problema na API?

**Comment by deploy-organizze** [comment]
Bom dia. Tudo bem?

Aqui é a Lud, do time de suporte.

Como a nossa api é pública fica difícil para dar suporte para
esse tipo de caso específico. Mas de qualquer forma, vamos dar
uma olhada para ver se é um problema geral ou só acontece na sua
conta, tá bem?

Abraços!

--

Suporte Organizze

www.organizze.com.br ( https://www.organizze.com.br )

organizze/api-doc on June 13, 2019 at 8:08pm wrote:

Tenho uma movimentação realizada no meu cartão de crédito
no dia 31/05.

O fatura é fechada no dia 30 de cada mês, então esse lançamento
aparecerá somente na fatura paga em julho.

Ao requisitar o endereço
https://api.organizze.com.br/rest/v2/transactions?start_date=2019-05-01&end_date=2019-05-31
a movimentação não é retornada.

Ao tentar requisitar as movimentações do mês seguinte essa
movimentação também não aparece.

Estou fazendo algo errado ou é algum problema na API?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/organizze/api-doc/issues/25?email_source=notifications&email_token=AARPEL2B7WT4RMUPOOZCXUDP2LHP3A5CNFSM4HYBELJKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GZN3YPQ )
, or mute the thread

**Comment by esdras** [comment]
Oi @gabrielhof 

Aqui é o Esdras do time do desenvolvimento, a gente já colocou esta issue no nosso pipeline aqui. Observe que movimentações de cartão de crédito se comportam de forma um pouco diferente das outras movimentações.

Como o endpoint `/transactions` lida com as movimentações de conta bancária, provavelmente você vai encontrar a movimentação feita no cartão somente no endpoint de faturas de cartão:

https://github.com/organizze/api-doc#detalhar-uma-fatura-de-cart%C3%A3o-de-cr%C3%A9dito

Eventualmente a gente vai fazer um endpoint que lista todas as movimentações, inclusive as de cartão de crédito, por regime de competência.

Nossa documentação não está clara quanto a isso, e eu peço desculpas pelo transtorno.

**Comment by alexwbuschle** [comment]
Deu tudo certo @gabrielhof ?

**Comment by gabrielhof** [comment]
Desculpe pela demora. Não recebi nenhuma notificação no meu email.
Entendi @esdras. Vou buscar as movimentações do cartão de crédito em separado.

**Comment by alexwbuschle** [comment]
Beleza, to fechando a issue.

Qualquer coisa só avisar.
